### ISSUE TITLE
Force Field does not update on explosions

### ISSUE THREAD

**Issue by prasselpikachu** [BuiltBrokenModding/MFFS_Classic#10]
Happens with both TNT and ICBM rockets/missiles

Triggering a block update manually near the force field makes it update however

**Comment by DarkGuardsman** [comment]
ICBM support has not been added yet, and not sure about TNT. I'll have someone check into it first chance I get.

**Comment by Pwalne** [comment]
The underlying issue of the forcefield not updating has todo with a VoltzIssue

**Comment by Pwalne** [comment]
Latest commit should fix this, will leave issue upon incase it still arises.
