### ISSUE TITLE
Textures don't load in a development environment using IntelliJ

### ISSUE THREAD

**Issue by prasselpikachu** [BuiltBrokenModding/MFFS_Classic#11]
Workaround: manually copy assets directory to build/classes/main/

Fix: follow the instructions at http://stackoverflow.com/questions/27623326/minecraft-forge-not-loading-textures

The solution there says it's a problem with just IntelliJ - I wonder why the fix is done in the build.gradle though

**Comment by DarkGuardsman** [comment]
Mark your resource folder as a source folder
