### ISSUE TITLE
I cant charge coercion deriver

### ISSUE THREAD

**Issue by Serch28** [BuiltBrokenModding/MFFS_Classic#12]
i can´t use RF on coercion deriver, please help, im on 1.7.10 with the last of 1.7.10, i can't change unit from MegaWatts to RF http://prntscr.com/dsathz

**Comment by Pwalne** [comment]
The Units are irrelevant to the actual charging, really just their for reference. 

You need to provide more information as a most RF devices charge it.  What mod is the item being used to charge it from, what item exactly is it?

**Comment by Serch28** [comment]
im trying using a creative motor of buildcraft

**Comment by Serch28** [comment]
i solved the problem, thanks.
