### ISSUE TITLE
ForceField Renderer crash

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BuiltBrokenModding/MFFS_Classic#13]
https://gist.github.com/71107be189b77c7f4ddffd0642ea234f
again crash.
put field "cube" with a radius of 5
the map can not go. constantly this crash. remove the mod everything is OK.

**Comment by Pwalne** [comment]
You need to provide more information to replicate the issue. As the cube mode works fine for me. Make sure to look at the server logs if you are on a server, and that you are updated to the latest version of mffs & VoltzEngine.

**Comment by prasselpikachu** [comment]
I am getting this crash on the latest commit, however I made a sphere with 17 scale modules.

I believe this crash is happening randomly - ive  had it multiple times so far and i cant seem to pin down a common cause for these crashes

**Comment by DarkGuardsman** [comment]
If you have optifine or fastcraft try removing those and see if the error clears up. 

Other than that we are looking into the issue but it will take a while to hunt down.

**Comment by prasselpikachu** [comment]
As can be seen from the OP's log, he is neither using any of those.

I am running only MFFS in a development environment, so it is the only mod I am running in this instance.

Debugging is going to be hard though :/

**Comment by SvEgiiVEteR** [comment]
@DarkGuardsman I don't have them for a long time

**Comment by SvEgiiVEteR** [comment]
# Enables/Disables the renderer used for the forcefield block. [default: true]
    B:"Use Forcefield Renderer"=false
all is well....I hope so now))
