### ISSUE TITLE
Forton Capacitor Not Storing Energy

### ISSUE THREAD

**Issue by xSelseor** [BuiltBrokenModding/MFFS_Classic#15]
Running through the mods in my modpack to ensure they work and have been having issues with the Forton Capacitor not storing any energy. We are running the latest version.

Here is a GIF of what is occuring: https://gyazo.com/984b56cd6da80aed53d078c41f3ec3e4

With Capacity & Speed Upgrades: https://gyazo.com/070edda75083c96563434c90bfc7ca31

Capacitor set to fill mode: https://gyazo.com/96696703d5252c578cae09f45ad1408e

Capacitor set to fill mode with infinite power card (connected to nothing): https://gyazo.com/7c30316c1951e4a5f6371d8738492573

I even attempted to alter the config and turned the base consumption down to '0' and the power drain continues.

**Comment by Pwalne** [comment]
This issue is related to #14 and will be dealt with next update. The capacitor will be reverted to a slight modified original while a new power consumption model is considered.
