### ISSUE TITLE
Frequency Card and Identification Card have the same recipe

### ISSUE THREAD

**Issue by Skkubah** [BuiltBrokenModding/MFFS_Classic#17]
Greetings,
I've discovered this a while ago, trying to use the recipe only makes the Frequency Card.

Here are some screenshots from NEI:

![2017-01-31_22 15 13](https://cloud.githubusercontent.com/assets/10351506/22620667/e6e2a91c-eaf7-11e6-9568-2a183b4cf500.png)

![2017-01-31_22 15 15](https://cloud.githubusercontent.com/assets/10351506/22620669/e98464da-eaf7-11e6-883e-7096ffc8cdcc.png)

Thank you for your time.

**Comment by Pwalne** [comment]
It seems they were, Although one is suppose to be Wire Card Wire, the Wire will revert to redstone if a wire equivalent does not exist. Therefore I have adjusted the ID card recipe slightly to require 4 redstone and a card.

Thank you for the report.
