### ISSUE TITLE
ForceField Block is using energy but the Force Fields will not show up 

### ISSUE THREAD

**Issue by Avenger1994** [BuiltBrokenModding/MFFS_Classic#22]
The Force Field block is using energy but for some odd reason whenever it's turned on the force field will not generate

**Comment by Pwalne** [comment]
Your description of your issue is not clear. If you can provide more information such as but not limited to:

- Screenshots

- Procedure to replicate issue

I would be more than happy to further investigate the problem that is at hand.

**Comment by Avenger1994** [comment]
Never Mind I was watching an old  MFFS review. Found a more recent version that works now
