### ISSUE TITLE
Aren't that much tiles is bad for server and TPS?

### ISSUE THREAD

**Issue by sliterok** [BuiltBrokenModding/MFFS_Classic#23]
Before loading chunks with FF
![mffslag2](https://cloud.githubusercontent.com/assets/12751644/24836752/ec877e4c-1d3d-11e7-926c-1f9813a2799d.png)
After loading chunks with FF
![mffslag1](https://cloud.githubusercontent.com/assets/12751644/24836751/ec6bdca0-1d3d-11e7-9190-3f3e64c605d0.png)

**Comment by DarkGuardsman** [comment]
Not really, from your own test your TPS only dropped slightly. As well TPS is not really affected by the number of tiles but by how much data is processed per tick. In the case of MFFS it only checks if the host is alive every so many ticks. Additionally, this is one of the only way to ensure the forcefield blocks die off. The other option would kill servers by having the block use metadata to decay.
