### ISSUE TITLE
Anti-Personnel module kills everybody regardless of Biometric Identifier settings

### ISSUE THREAD

**Issue by sliterok** [BuiltBrokenModding/MFFS_Classic#24]
![image](https://cloud.githubusercontent.com/assets/12751644/24836910/ce37da78-1d41-11e7-992a-07f53e5d260c.png)
![image](https://cloud.githubusercontent.com/assets/12751644/24836912/d66a703e-1d41-11e7-851c-860faad6c10b.png)
![image](https://cloud.githubusercontent.com/assets/12751644/24836916/e19732bc-1d41-11e7-9455-015d92311a4e.png)

**Comment by DarkGuardsman** [comment]
The permission system needs to be worked over in the mod. I should be doing a pass on the mod here soon and will fix this is when I do. In the mean time if @Pwalne is free he can fix it.

**Comment by Pwalne** [comment]
Make sure the permission: 'BYPASS_DEFENSE' is set. The permissions are kind of confusing, and as stated will need to be reworked.

**Comment by DarkGuardsman** [comment]
I forgot to reply on this, I reworked the permission GUI to reduce the confusion. I also tested all of the settings and they do work. What most likely happened is you missed the setting due to no scroll bar existing. The new version includes a scrollbar to indicate more options.
