### ISSUE TITLE
Works Fine On Client, Crashes Servers

### ISSUE THREAD

**Issue by GippoHippo** [BuiltBrokenModding/MFFS_Classic#25]
The mod works fine and runs ok on the client but if you try to put it in any server files, it causes a crash.
[https://pastebin.com/caMi7yuC](url)

**Comment by DarkGuardsman** [comment]
Make sure the server has the latest CodingLib installed. http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/

**Comment by GippoHippo** [comment]
Adding that just created a second error: https://pastebin.com/4tKi9wGe

**Comment by DarkGuardsman** [comment]
It's a problem with bukkit, disable the ASM testing in the config should let it run. However, most of the ASM patching will fail eventually as it's not designed to run on bukkit servers. The good thing is the game will not crash, bad news some events will fail to fire. This will cause mods like MFFS to function oddly.
