### ISSUE TITLE
Getting Client Crashes

### ISSUE THREAD

**Issue by sfxworks** [BuiltBrokenModding/MFFS_Classic#33]
When turning the forcefield on, putting in upgrades and getting too close to the forcefield, the client crashes.

Crash report:
https://github.com/TBGN/lapitos-server/issues/8

**Comment by DarkGuardsman** [comment]
Going to say its either a cauldran or fastcraft issue 

Especially since the line its crashing on its a vanilla call to get the tile entity. https://github.com/BuiltBrokenModding/MFFS_Classic/blob/master/src/main/java/com/builtbroken/mffs/content/field/BlockForceField.java#L346

**Comment by DarkGuardsman** [comment]
Added a temp fix that might solve the problem, but its not a real fix. What it will do is catch the crash the first 5 times and then suppress the error. This should prevent the game from failing but will cause render problems.

**Comment by clienthax** [comment]
@DarkGuardsman

**Comment by xJon** [comment]
Any update? This crash is still happening even in the latest build.

**Comment by Su5eD** [comment]
This is now outdated as we dropped 1.7.10 in favor of the rewrite.
