### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/MFFS_Classic#34]
https://pastebin.com/PWF27tkn
Any idea?

**Comment by Blueletric** [comment]
Closing because it is a repeat of another crash brought up by our dev team

**Comment by dmodoomsirius** [comment]
Duplicate of https://github.com/BuiltBrokenModding/MFFS_Classic/issues/33

**Comment by xJon** [comment]
I'm using the latest public build of MFFS and this is not fixed, will you release the fix soon?
