### ISSUE TITLE
GUI's are missing many textures 1.7.10

### ISSUE THREAD

**Issue by kmecpp** [BuiltBrokenModding/MFFS_Classic#38]
The GUI's are still missing many of the old components. The projector is just one example:

![image](https://user-images.githubusercontent.com/6520738/43786979-f049017c-9a37-11e8-9ade-5c7a4ff341a2.png)

**Comment by Breadabix** [comment]
I am having issues with this atm, trying to hollow out a giant sphere but cant see half of what I need to.

**Comment by DarkGuardsman** [comment]
For the most part the mod was never finished for its port to 1.7 and the devs I keep putting in charge are not doing work.
