### ISSUE TITLE
[Bug] Fortron Capacitor deletes items on input

### ISSUE THREAD

**Issue by JKohlman** [BuiltBrokenModding/MFFS_Classic#54]
Hi there,

I was playing around with the Interdiction Matrix and unfortunately discovered this rather bad bug, losing an entire inventory to it in the process.

Versions:
Game 1.19.2
MFFS 5.0.0
Forge 43.2.14

The Fortron Capacitor will accept and permanently delete any item added to it's inventory via almost any means besides the player. This means that hoppers, an interdiction matrix item confiscation module, pipes, etc all push items successfully into the capacitor but they are gone and not dropped when it gets broken.

I'm not sure how it works with hoppers/pipes but as far as the interdiction matrix confiscation this simply checks if the nearby block has the capability `ForgeCapabilities.ITEM_HANDLER` and then inserts the item (see `InventoryBlockEntity mergeIntoInventory`).

To recreate it is as simple as placing a hopper into the capacitor and putting an item in.

![image](https://github.com/BuiltBrokenModding/MFFS_Classic/assets/2236351/e99f6cc3-0c7e-4620-be96-c61e7cdf9205)

**Comment by Su5eD** [comment]
Fixed in releases [1.20.1-5.1.5](https://legacy.curseforge.com/minecraft/mc-mods/mffs/files/4691196) and [1.19.2-5.0.1](https://legacy.curseforge.com/minecraft/mc-mods/mffs/files/4691211). Can you please confirm this?

**Comment by JKohlman** [comment]
That does seem to resolve the items getting deleted thank you very much!
